version: '3.8'

services:
  # rename?
  web:
    build: .
    depends_on:
      - elasticsearch
      - mysql
    command: bin/rails server --binding 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      - DB_HOST=mysql
      - ES_HOST=elasticsearch:9200


  # TODO: COPY SECRETS

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms750m -Xmx750m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.9
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  mysql:
    image: mysql:5.6
    volumes:
      - ./docker/my.cnf:/etc/my.cnf
      - db_data:/var/lib/mysql/data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root

  redis:
    image: redis:5.0.9
    ports:
      - 6379:6379

volumes:
  es_data:
  db_data:
  gem_cache:
