version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    container_name: sg_es_68
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster-68
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9268:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:6.8.7
    container_name: sg_kib_68
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
